ansible_username: ec2-user
ansible_password: DevOps321
mongodb_host: mongodb-{{ env }}.sowjanya.fun
redis_host: redis-{{ env }}.sowjanya.fun
rabbitmq_host: rabbitmq-{{ env }}.sowjanya.fun
mysql_host: mysql-{{ env }}.sowjanya.fun

catalogue_host: catalogue.backend-alb-{{ env }}.sowjanya.fun
user_host: user.backend-alb-{{ env }}.sowjanya.fun
cart_host: cart.backend-alb-{{ env }}.sowjanya.fun
shipping_host: shipping.backend-alb-{{ env }}.sowjanya.fun
payment_host: payment.backend-alb-{{ env }}.sowjanya.fun
app_version: v3
