- name: app setup
  #tags: 
  #- deployment
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: java setup
  #tags: 
  #- deployment
  ansible.builtin.import_role:
  #ansible.builtin.include_role:
    name: common
    tasks_from: java-setup.yaml

- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml

- name: install mysql dependancies
  ansible.builtin.pip:
     name: "{{ item }}"
     executable: pip3.9
  loop:
    - PyMySQL
    - cryptography


    
- name: import shipping data
  community.mysql.mysql_db:
      state: import
      name: all
      login_host: "{{ mysql_host }}"
      login_user: root
      login_password: RoboShop@1
      target: "{{ item }}"
  loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql

- name: start and enable shipping
  ansible.builtin.service:
      name: shipping
      state: started
      enabled: yes

    
 