[mongodb]
localhost

[catalogue]
catalogue-dev.sowjanya.fun

[redis]
localhost

[user]
user-dev.sowjanya.fun

[cart]
cart-dev.sowjanya.fun

[mysql]
mysql-dev.sowjanya.fun

[shipping]
shipping-dev.sowjanya.fun

[payment]
payment-dev.sowjanya.fun

[rabbitmq]
rabbitmq-dev.sowjanya.fun

[frontend]
frontend-dev.sowjanya.fun

[local]
localhost