[mongodb]
localhost

[catalogue]
localhost

[redis]
localhost

[user]
localhost

[cart]
localhost

[mysql]
localhost

[shipping]
localhost

[payment]
localhost

[rabbitmq]
localhost

[frontend]
localhost

[local]
localhost