#MYSQL_ROOT_PASSWORD: "{{ lookup('amazon.aws.aws_ssm', '/roboshop/dev/mysql_password', region='us-east-1', decrypt=False ) }}"
#"{{ (lookup('amazon.aws.aws_secret', '/roboshop/dev/mysql_password', region='us-east-1') | from_json).MYSQL_ROOT_PASSWORD }}"

#"{{ lookup('amazon.aws.aws_ssm', '/roboshop/dev/mysql_password', region='us-east-1', decrypt=False ) }}"